# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
