# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
