# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 11:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 28, 11, 29, 16, 402000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 28, 11, 29, 25, 732000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=datetime.datetime(2016, 7, 28, 11, 29, 34, 520000, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
