# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160728_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_modified',
        ),
    ]
