# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160912_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary_content',
            field=models.TextField(default='Email Summary'),
        ),
    ]
