# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 17:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20160915_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
