# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20160922_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='Name',
            new_name='name',
        ),
    ]
