# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20160927_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-name']},
        ),
    ]
